### ISSUE TITLE
余分な箇所

### ISSUE THREAD

**Issue by 43zaki** [c0b2116968/ProjExD#11]
https://github.com/c0b2116968/ProjExD/blob/89bcb072ef1aa1af2f3beba490af91e5e00020ac/ex03/maze.py#L14
14行目から33行目を
if key == "Up" and maze_source[my-1][mx] != 1:
        my -= 1
    elif key == "Down" and maze_source[my+1][mx] != 1:
        my += 1
    elif key == "Left" and maze_source[my][mx-1] != 1:
        mx -= 1
    elif key == "Right" and maze_source[my][mx+1] != 1:
        mx += 1
        
    cx = mx*100 + 50
    cy = my*100 + 50
   こういう感じでかいてみてみたら

**Comment by c0b2116968** [comment]
ありがとうございます、修正します
